plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

version = project.mod_version + "+" + stonecutter.current.version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = "https://maven.parchmentmc.org" }
    maven { url = "https://maven.terraformersmc.com/" }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.wispforest.io/releases/" }
    maven { url = "https://maven.fzzyhmstrs.me/"}
    maven { url = "https://maven.bawnorton.com/releases" }
    maven { url = "https://maven.kyrptonaught.dev" }
    maven { url = "https://repo.greenhouse.house/releases/" }
    maven { url = "https://maven.gegy.dev" }
    maven { url = "https://raw.githubusercontent.com/Aton-Kish/mcmod/maven" }
    maven { url = "https://jitpack.io/" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${stonecutter.current.project}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${property("parchment_version")}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${property("loader_version")}"

    // Hard dependencies
    modImplementation "net.fabricmc.fabric-api:fabric-api:${property("fabric_version")}"
    include(implementation "com.moulberry:mixinconstraints:${project.mixinconstraints_version}")
    modImplementation "com.terraformersmc:modmenu:${property("modmenu_version")}"
    modImplementation "me.fzzyhmstrs:fzzy_config:${property("fzzy_version")}"
    modImplementation("io.wispforest:accessories-fabric:${property("accessories_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modImplementation("io.wispforest:owo-lib:${property("owo_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }

    // Supported mods
    modLocalRuntime("dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${property("ldl_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:serene-seasons:${property("sereneseasons_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:raised:${property("raised_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:notes:${property("notes_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:friends-and-foes:${property("friendsandfoes_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:reinforced-shulker-boxes:${property("rsb_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("atonkish.reinfcore:reinforced-core:${property("rfcore_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }

    // 1.20.1 exclusive supported mods
    if (stonecutter.eval(stonecutter.current.version, "1.20.1")) {
        modCompileOnly("maven.modrinth:sodium-dynamic-lights:${property("sdl_version")}") {
            exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
        }
    }

    // 1.21.1 exclusive supported mods
    if (stonecutter.eval(stonecutter.current.version, "1.21.1")) {
        modCompileOnly "vectorwing:FarmersDelight:${property("fdrf_version")}"
        modCompileOnly "maven.modrinth:fragmentum:${property("fragmentum_version")}"
        modCompileOnly "maven.modrinth:ars-elixirum:${property("arselixirum_version")}"
    }
    modCompileOnly("maven.modrinth:eleron:${property("eleron_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }

    // 1.20.1-1.21.1 exclusive supported mods
    if (stonecutter.eval(stonecutter.current.version, ">= 1.20.1 <= 1.21.1")) {
        modCompileOnly "net.kyrptonaught:customportalapi:${property("customportalapi_version")}"
        modCompileOnly "maven.modrinth:deeperdarker:${property("deeperdarker_version")}"
    }
    modCompileOnly("maven.modrinth:fabric-seasons:${property("fabricseasons_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:fabric-seasons-extras:${property("fabricseasonsextras_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modCompileOnly("maven.modrinth:extrasoundsforge:${property("extrasounds_version")}") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }

    if (stonecutter.eval(stonecutter.current.version, "1.21.1")) {
        modCompileOnly files("ext_imports/citresewn-defaults-1.2.2+1.21.jar")
        modCompileOnly "maven.modrinth:cit-resewn:${property("citresewn_version")}"
        modCompileOnly "vectorwing:FarmersDelight:${property("fdrf_version")}"
        modCompileOnly "maven.modrinth:deeperdarker:${property("deeperdarker_version")}"
        modCompileOnly "maven.modrinth:fragmentum:${property("fragmentum_version")}"
        modCompileOnly "maven.modrinth:ars-elixirum:${property("arselixirum_version")}"
        modCompileOnly "maven.modrinth:extrasoundsforge:${property("extrasounds_version")}"
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft", stonecutter.current.version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft": stonecutter.current.version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = stonecutter.eval(stonecutter.current.version, ">=1.20.5") ? 21 : 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
    def java = stonecutter.eval(stonecutter.current.version, ">=1.20.5")
            ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17
    targetCompatibility = java
    sourceCompatibility = java
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

stonecutter {
    swaps["accessory"] = eval(current.version, "< 1.21.8")
            ? "import io.wispforest.accessories.api.Accessory;"
            : "import io.wispforest.accessories.api.core.Accessory;"
    swaps["accessory_registry"] = eval(current.version, "< 1.21.8")
            ? "import io.wispforest.accessories.api.AccessoryRegistry;"
            : "import io.wispforest.accessories.api.core.AccessoryRegistry;"
    swaps["accessory_renderer"] = eval(current.version, "< 1.21.8")
            ? "import io.wispforest.accessories.api.client.AccessoryRenderer;"
            : "import io.wispforest.accessories.api.client.renderers.AccessoryRenderer;"
    swaps["simple_accessory_renderer"] = eval(current.version, "< 1.21.8")
            ? "import io.wispforest.accessories.api.client.SimpleAccessoryRenderer;"
            : "import io.wispforest.accessories.api.client.renderers.SimpleAccessoryRenderer;"
    swaps["expanded_simple_container"] = eval(current.version, "< 1.21.8")
            ? "import io.wispforest.accessories.impl.ExpandedSimpleContainer;"
            : "import io.wispforest.accessories.impl.core.ExpandedContainer;"
}

publishMods {
    file = remapJar.archiveFile
    changelog = file(getRootDir().path + "/CHANGELOG.md").text
    type = STABLE
    modLoaders.add("fabric")
    displayName = project.mod_version + " for Fabric " + stonecutter.current.version

    modrinth {
        accessToken = providers.environmentVariable("MR_KEY")
        projectId = "CVRzrXGP"
        minecraftVersions.add(stonecutter.current.version)
        requires("fabric-api", "fzzy-config", "accessories")
        optional("modmenu", "lambdynamiclights")
    }

    curseforge {
        accessToken = providers.environmentVariable("CF_KEY")
        projectId = "1169634"
        minecraftVersions.add(stonecutter.current.version)
        javaVersions.add(stonecutter.eval(stonecutter.current.version, ">=1.20.5")
                ? JavaVersion.VERSION_21 : JavaVersion.VERSION_17)
        clientRequired = true
        serverRequired = true
        requires("fabric-api", "fzzy-config", "accessories")
        optional("modmenu", "lambdynamiclights")
    }
}