# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.16.14
parchment_version=[VERSIONED]
# Mod Properties
mod_version=2.2.1
maven_group=me.pajic
archives_base_name=accessorify
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=[VERSIONED]
mixinconstraints_version=1.1.0
modmenu_version=[VERSIONED]
fzzy_version=[VERSIONED]
owo_version=[VERSIONED]
accessories_version=[VERSIONED]
ldl_version=[VERSIONED]

customportalapi_version=[VERSIONED]
sereneseasons_version=[VERSIONED]
fabricseasons_version=[VERSIONED]
fabricseasonsextras_version=[VERSIONED]
raised_version=[VERSIONED]
fdrf_version=[VERSIONED]
notes_version=[VERSIONED]
deeperdarker_version=[VERSIONED]
friendsandfoes_version=[VERSIONED]
citresewn_version=[VERSIONED]
eleron_version=[VERSIONED]
fragmentum_version=[VERSIONED]
arselixirum_version=[VERSIONED]
rsb_version=[VERSIONED]
rfcore_version=[VERSIONED]
extrasounds_version=[VERSIONED]