org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.2
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=accessorify
mod_name=Accessorify
mod_license=MIT
mod_version=2.0.0
mod_group_id=me.pajic
mod_authors=pajic
mod_description=Makes some vanilla items more useful using the Accessories API

fapibase_version=0.4.31+ef105b4977
fresloader_version=0.11.10+bcd08ed377
accessories_version=1.0.0-beta.47+1.20.1
fzzy_version=0.7.0+1.20.1+forge