neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.02.16
minecraft_version=1.21.4
minecraft_version_range=[1.21.2,1.21.4]
neo_version=21.4.92-beta
accessories_version=1.2.18-beta+1.21.4
owo_version=0.12.19-beta.2+1.21.4

sereneseasons_version=10.4.0.2-neoforge,1.21.4
raised_version=NeoForge-1.21.3-4.0.1
notes_version=1.21.4-3.0.1-neoforge
deeperdarker_version=1.3.4-neoforge+1.21
friendsandfoes_version=neoforge-mc1.21.1-3.0.6